language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t namlt3820/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true namlt3820/react-test npm test
after_success:
  - docker build -t namlt3820/multi-client ./client
  - docker build -t namlt3820/multi-nginx ./nginx
  - docker build -t namlt3820/multi-server ./server
  - docker build -t namlt3820/multi-worker ./worker

  -  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

  - docker push namlt3820/multi-client:latest
  - docker push namlt3820/multi-nginx:latest
  - docker push namlt3820/multi-server:latest
  - docker push namlt3820/multi-worker:latest
deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-634549447032
  bucket_path: multi_docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY